### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by Wut3054** [Beer-Network/beer-blockchain#1]
Request Node please

**Comment by petpoy** [comment]
i need IP address full node  conncet

**Comment by Wut3054** [comment]
Discord server ?
service and infomation

**Comment by RusWTz** [comment]
I need node!!!!!!!!!!!!!!!

**Comment by petpoy** [comment]
wallet not receive

**Comment by pentastra** [comment]
sometime syncing is stopping. needs more nodes.

**Comment by pentastra** [comment]
93.55.210.51

82.26.152.25

109.61.158.65
