### ISSUE TITLE
[BUG] Syncing problem

### ISSUE THREAD

**Issue by Jsewill** [Beer-Network/beer-blockchain#2]
Since the plot filter change, when attempting to sync from a fresh installation, the full node refuses to connect due to what it thinks is an invalid chain:

``` line 262, in short_sync_batch
    raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
ValueError: Error short batch syncing, failed to validate blocks 0-32

2021-08-06T02:04:27.627 full_node full_node_server        : WARNING  Banning <IP REDACTED> for 10 seconds```

**Comment by Beer-Network** [comment]
I just reboot the full node, try it now

**Comment by Jsewill** [comment]
My harvester is somehow checking plots (farming), while my farmer is still looking for the initial chain. Do you have a full node address to which I could connect?

**Comment by Jsewill** [comment]
I'm connected to two peers, but no initial chain. I'm getting a lot of these from the log:

```2021-08-06T02:21:51.858 full_node full_node_server        : INFO     Cannot connect to host introducer.beernetwork.org:5899 ssl:<ssl.SSLContext object at 0x7fd364108830> [Name or service not known]```

**Comment by Jsewill** [comment]
While `beer show -sc` says I don't even have an initial chain, I did see the log said I finished signage point 16/64, and added a block. The harvester checked plots for proofs once. It hasn't done anything since.

When you can, it would be excellent if you could post an IP for that full node to which I should connect.

**Comment by Jsewill** [comment]
My farmer shows that it is synced now at a height of 1, and `beer farm summary` reports that it is farming. The harvester looks like it is connected and operating correctly.
